### ISSUE TITLE
why is travis failing?

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/decido#3]
I'd expect this is C++11 problems, but now have SystemRequirements, Makevars and environment variable in travis.yml ...

```
/usr/include/c++/4.8/bits/stl_vector.h:901:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const value_type& {aka const std::array<double, 2ul>&}’
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = std::array<double, 2ul>; _Alloc = std::allocator<std::array<double, 2ul> >; std::vector<_Tp, _Alloc>::value_type = std::array<double, 2ul>]
       push_back(value_type&& __x)
       ^
/usr/include/c++/4.8/bits/stl_vector.h:919:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘std::vector<std::array<double, 2ul> >::value_type&& {aka std::array<double, 2ul>&&}’
make: *** [decido.o] Error 1
ERROR: compilation failed for package ‘decido’
* removing ‘/home/travis/build/hypertidy/decido/decido.Rcheck/decido’
```

**Comment by virgesmith** [comment]
Suggest* changing `poly.push_back({pt});` to `poly.push_back(pt);` at decido.cpp:46? You're pushing a single element so not quite sure why the initialiser list syntax is there.
* based on reading the code not compiling it!

**Comment by mdsumner** [comment]
Thanks!  That fixed the Linux build, though osx is still failing. 

I'm going to put this aside for day or so, but I appreciate the feedback!

**Comment by virgesmith** [comment]
I think (some of) the OSX errors will go away if you explicitly `#include <array>` in earcut_hpp.cpp.
What's the intent of earcut_hpp.cpp? It looks like a header and it's being #included like a header, so dont get why the cpp extension?

**Comment by mdsumner** [comment]
Oh that's just me not knowing what I'm doing!  Mapbox calls it   .hpp but check complains about that. I guess it should be  .h  Thanks again, will try

**Comment by mdsumner** [comment]
PASS!  Thanks so much ;)   (BTW, If you are trying to actually use this the logic for the geometry input is a bit iffy still but I'll get to that soon).
